# Generated by Django 6.0 on 2026-02-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
