# Generated by Django 6.0 on 2026-02-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientprofile_bio_clientprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
