# Generated by Django 5.2.10 on 2026-02-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_hiringrequest'),
        ('tutor', '0002_alter_availability_id_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrequest',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_hiring_requests', to='tutor.tutorprofile'),
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
