# Generated by Django 5.2.10 on 2026-02-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
