# Generated by Django 5.2.10 on 2026-02-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_profile_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
