# Generated by Django 5.2.10 on 2026-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
