# Generated by Django 5.2.10 on 2026-02-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentprofile_profile_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_reviews',
        ),
    ]
