# Generated by Django 5.2.10 on 2026-02-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_bio_profile_rating_profile_skills_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
