# Generated by Django 5.0.1 on 2026-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_availability_id_alter_skill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='github_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='teaching_skills',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
