# Generated by Django 5.2.10 on 2026-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_availability_id_alter_skill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
