# Generated by Django 5.2.10 on 2026-02-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='skill',
        ),
        migrations.AddField(
            model_name='availability',
            name='skill_name',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
    ]
