# Generated by Django 5.2.10 on 2026-02-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutorprofile_github_profile_and_more'),
        ('tutor', '0005_rename_slot_booking_availability_booking_status_and_more'),
    ]

    operations = [
    ]
