# Generated by Django 5.2.10 on 2026-02-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_merge_20260210_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='linkedin',
        ),
    ]
